### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by githubteacher** [githubschool/apr-03#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'unsubscribe' button.

**Comment by beardofedu** [comment]
Hello! 👋

**Comment by nesmarashad** [comment]
Hello 👍

**Comment by medhatali** [comment]
hi

**Comment by RafifZayedV** [comment]
hi

**Comment by engpop** [comment]
Hello :)

**Comment by AmiraNagi** [comment]
Hello

**Comment by Mo7medFouad** [comment]
Hi

**Comment by marwaGoda** [comment]
Hi :)

**Comment by DinaFransis** [comment]
hi :)

**Comment by hisham-elbreky** [comment]
Hi :)

**Comment by bsalam** [comment]
HI :)
